# Generated by Django 3.0.3 on 2020-08-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_recommender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='anime_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='anime',
            name='episode',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='anime',
            name='member',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='anime',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
