# Generated by Django 3.0.3 on 2020-08-04 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_recommender', '0003_auto_20200804_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('anime_id', models.IntegerField()),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
